---
title: "Figura ges prestaciones lme"
output: html_document
---


```{r LIBRERIAS, message=FALSE, warning=FALSE, include=FALSE}
library(data.table)
library(tidyverse)
library(ggpubr)
library(haven)
```

# Datos

## GES agregados, por sexo y previsión
```{r}
dat.todos <- as.data.table(read_dta("diag confirms/output/DB/all cancers observed predicted counterfactual.dta"))[, cancer := "All Cancers"]

dat.mama <- as.data.table(read_dta("diag confirms/output/DB/Cáncer de mamas (tabla con observados, predichos y contrafactual).dta"))[, cancer := "Breast Cancer"]

dat.test <- as.data.table(read_dta("diag confirms/output/DB/Cáncer de testículo (tabla con observados, predichos y contrafactual).dta"))[, cancer := "Testicular Cancer"]

dat.cerv <- as.data.table(read_dta("diag confirms/output/DB/Cervix cancer (tabla con observados, predichos y contrafactual).dta"))[, cancer := "Cervical Cancer"]

dat.colo <- as.data.table(read_dta("diag confirms/output/DB/Cáncer colorectal (tabla con observados, predichos y contrafactual).dta"))[, cancer := "Colorectal Cancer"]

dat.gast <- as.data.table(read_dta("diag confirms/output/DB/Cáncer gástrico (tabla con observados, predichos y contrafactual).dta"))[, cancer := "Gastric Cancer"]

dat.leuk <- as.data.table(read_dta("diag confirms/output/DB/Leucemia (tabla con observados, predichos y contrafactual).dta"))[, cancer := "Leukemia"]

dat.lymp <- as.data.table(read_dta("diag confirms/output/DB//Linfoma (tabla con observados, predichos y contrafactual).dta"))[, cancer := "Lymphoma"]

dat <- rbind(dat.cerv, dat.colo, dat.gast, dat.leuk, dat.lymp, dat.mama, dat.test, dat.todos)

dat.todos.sex <- as.data.table(read_dta("diag confirms/output/DB/all cancers observed predicted counterfactual by sex.dta"))[, cancer := "All Cancers"]

dat.todos.prev <- as.data.table(read_dta("diag confirms/output/DB/all cancers observed predicted counterfactual by insurance 1 missing.dta"))[, cancer := "All Cancers"]

rm(dat.cerv, dat.colo, dat.gast, dat.leuk, dat.lymp, dat.mama, dat.test, dat.todos)
```

```{r}
. <- dat[
  , sexo := factor(sexo, levels = 1:2, labels = c("Male", "Female")) ][
  , edad_cat := factor(rango_etario, levels = 1:7, labels = c("[20,30)", "[30,40)", "[40,50)", "[50,60)", 
                                                              "[60,70)", "[70,80)", "[80,90)"))  ][
  , edad_cat := relevel(edad_cat, "[40,50)")  ][
  , year := as.numeric(ano)  ][
  , week := as.factor(semana)  ][#ojo! estas semanas se construyeron de forma distinta: contiene 52 semanas por año en lugar de 53
  , time := as.numeric(t)  ][
  , pandemia := as.numeric(level)  ][
  , time_after := as.numeric(slope)  ][
  , count := as.numeric(`_freq`)  ][
  , yhat :=  as.numeric(nhat)][
  , ub :=  as.numeric(llim_nh)][
  , lb :=  as.numeric(ulim_nh)][
  , cf :=  as.numeric(nhat0)][
  , cf_ub :=  as.numeric(llim_nh0)][
  , cf_lb :=  as.numeric(ulim_nh0)][
  , grupo.trz :=  as.factor(cancer)][
  , .(week, year, sexo, edad_cat, count, pandemia, time, time_after, yhat, ub, lb, cf, cf_ub, cf_lb, grupo.trz) ]

dat.plots.agg <- .[grupo.trz == "All Cancers"][, -("grupo.trz")]
dat.plots.type <- droplevels.data.frame(.[grupo.trz != "All Cancers"])
dat.plots.type.sexo <- droplevels.data.frame(.[grupo.trz != "All Cancers"])
```

```{r}
dat.plots.agg.sexo <- dat.todos.sex[
  , sexo := factor(sexo, levels = 1:2, labels = c("Male", "Female")) ][
  , edad_cat := factor(rango_etario, levels = 1:7, labels = c("[20,30)", "[30,40)", "[40,50)", "[50,60)", 
                                                              "[60,70)", "[70,80)", "[80,90)"))  ][
  , edad_cat := relevel(edad_cat, "[40,50)")  ][
  , year := as.numeric(ano)  ][
  , week := as.factor(semana)  ][#ojo! estas semanas se construyeron de forma distinta: contiene 52 semanas por año en lugar de 53
  , time := as.numeric(t)  ][
  , pandemia := as.numeric(level)  ][
  , time_after := as.numeric(slope)  ][
  , count := as.numeric(`_freq`)  ][
  , yhat :=  as.numeric(nhat)][
  , ub :=  as.numeric(llim_nh)][
  , lb :=  as.numeric(ulim_nh)][
  , cf :=  as.numeric(contrafactual)][
  , cf_ub :=  as.numeric(llim_contra)][
  , cf_lb :=  as.numeric(ulim_contra)][
  , grupo.trz :=  as.factor(cancer)][
  , .(week, year, sexo, edad_cat, count, pandemia, time, time_after, yhat, ub, lb, cf, cf_ub, cf_lb, grupo.trz) ]
```

```{r}
dat.plots.agg.prev <- dat.todos.prev[
  , prevision := factor(prevision, levels = 1:2, labels = c("Public", "Private")) ][
  , prevision := relevel(prevision, "Private") ][
  , trimester := as.factor(trimestre)  ][#ojo! estas semanas se construyeron de forma distinta: contiene 52 semanas por año en lugar de 53
  , time := as.numeric(t)  ][
  , pandemia := as.numeric(level)  ][
  , time_after := as.numeric(slope)  ][
  , count := as.numeric(`_freq`)  ][
  , yhat :=  as.numeric(nhat)][
  , ub :=  as.numeric(llim_nh)][
  , lb :=  as.numeric(ulim_nh)][
  , cf :=  as.numeric(contrafactual)][
  , cf_ub :=  as.numeric(llim_contra)][
  , cf_lb :=  as.numeric(ulim_contra)][
  , grupo.trz :=  as.factor(cancer)][
  , .(trimester, prevision, count, pandemia, time, time_after, yhat, ub, lb, cf, cf_ub, cf_lb, grupo.trz) ]
```

## Prestaciones agregados

```{r DATA LABELS}
prest <- c("Oncology out-patient visits", "Cancer-related antigen test", "Biopsies", "Neoplastic Cells test" , "PET-CT", 
            "Fecal occult bleeding test", "Sigmoidoscopy and\nColonoscopy", 
            "Cervical Biopsy", "Colposcopy", "Papanicolaou", 
            "Esophagoscopy,\nGastroduodenoscopy,\nYeyuno Ileoscopy", "Ureasa tests", 
            "Breast Ultrasound", "Mammography", "Breast MRI",
            "Prostate-Specific\nAntigen", "Prostate Ultrasound")

prest.sexo <- c("Oncology out-patient visits", "Cancer-related antigen test", "Biopsies", "Neoplastic Cells test" , "PET-CT", 
            "Fecal occult bleeding test", "Sigmoidoscopy and\nColonoscopy", 
            "Esophagoscopy, Gastroduodenoscopy, Yeyuno Ileoscopy", "Ureasa tests")
```

```{r LOAD DATA PLOTS}
load("health services/output/DB/DB predichos nb sti.RData")
dat.plots.agg.prest <- dat.plots
```

## LME agregados

```{r DATA}

load(file = "sick leaves/output/DB/DB predichos nb sti.RData")

dat.plots.agg.lme<-dat.plots
```


# Figuras

## GES agregada, por sexo y previsión

```{r FIG1 POR SEXO y prev, fig.height=8, fig.width=5, message=FALSE, warning=FALSE}
g1.agg <- dat.plots.agg %>% 
  filter(year == 2020) %>% 
  group_by(week) %>% 
  summarise(count = sum(count),
            yhat = sum(yhat),
            cf = sum(cf),
            ub = sum(ub),
            lb = sum(lb),
            cf_ub = sum(cf_ub),
            cf_lb = sum(cf_lb) ) %>% 
  mutate(caida_abs = cf-yhat,
         caida_abs_ub = cf_ub-ub,
         caida_abs_lb = cf_lb-lb,
         caida_rel = caida_abs*100 /cf,
         caida_rel_ub = caida_abs_ub*100 /cf_ub,
         caida_rel_lb = caida_abs_lb*100 /cf_lb) %>% 

  ggplot(aes(x = as.numeric(week), y = caida_rel)) +

  geom_line() +
  geom_point(size = .7) +
  geom_ribbon(aes(ymin = caida_rel_lb, ymax = caida_rel_ub), alpha = .3) +

  scale_x_continuous(breaks = seq(5, 53, 6), expand = c(0,0)) +
  labs(y = "% diagnostic confirmations reduction", x = "Week", 
       subtitle = "", title = "Total cancer diagnostic confirmations") +
  geom_vline(xintercept = 11, linetype = "dotted", color = "red") + 
  theme_minimal() + 
  theme(legend.position = "right",
        axis.title = element_text(size = 8),
        axis.text = element_text(size = 8),
        plot.subtitle = element_text(size = 8),
        plot.title = element_text(size = 11, face = "bold"))

g2.agg <- dat.plots.agg.sexo %>% 
  filter(year == 2020) %>% 
  group_by(week, sexo) %>% 
  summarise(count = sum(count),
            yhat = sum(yhat),
            cf = sum(cf),
            ub = sum(ub),
            lb = sum(lb),
            cf_ub = sum(cf_ub),
            cf_lb = sum(cf_lb) ) %>% 
  mutate(caida_abs = cf-yhat,
         caida_abs_ub = cf_ub-ub,
         caida_abs_lb = cf_lb-lb,
         caida_rel = caida_abs*100 /cf,
         caida_rel_ub = caida_abs_ub*100 /cf_ub,
         caida_rel_lb = caida_abs_lb*100 /cf_lb) %>% 
  
  ggplot(aes(x = as.numeric(week), y = caida_rel)) +

  geom_point(aes(color = sexo), size = .7) +
  geom_line(aes(x = as.numeric(week), group = sexo, color = sexo)) +
  geom_ribbon(aes(ymin = caida_rel_lb, ymax = caida_rel_ub, group = sexo, fill = sexo), alpha = .3) +

    scale_x_continuous(breaks = seq(5, 53, 6), expand = c(0,0)) +
  labs(y = "% diagnostic confirmations reduction", x = "Week", fill = "Sex", color = "Sex", 
       subtitle = "", title = "Cancer diagnostic confirmations by sex") +
  geom_vline(xintercept = 11, linetype = "dotted", color = "red") + 
  theme_minimal() + 
  theme(legend.position = "right",
        axis.title = element_text(size = 8),
        axis.text = element_text(size = 8),
        plot.subtitle = element_text(size = 8),
        plot.title = element_text(size = 11, face = "bold"))

g3.agg <- dat.plots.agg.prev %>% 
  filter(time %in% 13:16) %>% 
  group_by(trimester, prevision) %>% 
  mutate(caida_abs = cf-yhat,
         caida_abs_ub = cf_ub-ub,
         caida_abs_lb = cf_lb-lb,
         caida_rel = caida_abs*100 /cf,
         caida_rel_ub = caida_abs_ub*100 /cf_ub,
         caida_rel_lb = caida_abs_lb*100 /cf_lb,
         sems = 13) %>% 
  uncount(sems) %>% 
  ungroup() %>% 
  mutate(semana = c(1:52, 1:52)) %>% 
  
  ggplot(aes(x = semana)) +

  geom_point(aes(y = caida_rel, color = prevision), size = .7) +
  geom_line(aes(x = semana, y = caida_rel, group = prevision, color = prevision)) +
  geom_ribbon(aes(ymin = caida_rel_lb, ymax = caida_rel_ub, group = prevision, fill = prevision), alpha = .3) +
  
#  coord_cartesian(xlim = c(0,4))+
  scale_x_continuous(breaks = seq(5, 53, 6), expand = c(0,0)) +
  labs(y = "% diagnostic confirmations reduction", x = "Week", fill = "Insurance", color = "Insurance", 
       subtitle = "", title = "Cancer diagnostic confirmations by insurance") +
  geom_vline(xintercept = 11, linetype = "dotted", color = "red") + 
  theme_minimal() + 
  theme(legend.position = "right",
        axis.title = element_text(size = 8),
        axis.text = element_text(size = 8),
        plot.subtitle = element_text(size = 8),
        plot.title = element_text(size = 11, face = "bold"))

g1.a <- ggarrange(g1.agg, ncol = 2, widths = c(4,1))

g1.ges <- ggarrange(g1.a, g2.agg, g3.agg, ncol = 1)
g1.ges

#ggsave(plot = g1,
#       filename = "output/plots/Figure 2 diag conf.pdf", 
#       device = "pdf", dpi = "retina", width = 5, height = 8)
```

## Prestaciones

```{r FIG1, fig.width=6, fig.height=9, message=FALSE, warning=FALSE}
g1.agg.prest <- dat.plots.agg.prest %>% 
  filter(mod.int == "Additive") %>% 
  mutate(exposicion = ifelse(year == 2020, "2020", "2018-2019")) %>% 
  group_by(week, year, exposicion) %>% summarise(count = sum(count),
                                                 yhat = sum(yhat),
                                                 cf = sum(cf),
                                                 ub = sum(ub),
                                                 lb = sum(lb),
                                                 cf_ub = sum(cf_ub),
                                                 cf_lb = sum(cf_lb) ) %>% 
  group_by(week, exposicion)%>% summarise(count = mean(count),
                                          yhat = mean(yhat),
                                          cf = mean(cf),
                                          ub = mean(ub),
                                          lb = mean(lb),
                                          cf_ub = mean(cf_ub),
                                          cf_lb = mean(cf_lb) ) %>% 
  ggplot(aes(x = week, y = count, fill = exposicion))+
  geom_point(alpha = .3, aes(color = exposicion), size = 1) +
  geom_line(aes(x = week, y = yhat, color = exposicion, group = exposicion, linetype = "Observed")) +
  geom_ribbon(aes(ymin = lb, ymax = ub, group = exposicion), alpha = .3) +
  geom_line(aes(x = week, y = cf, color = exposicion, group = exposicion, linetype = "Predicted counterfactual"), 
            size = .3, name = "bla") +
  geom_ribbon(aes(ymin = cf_lb, ymax = cf_ub, group = exposicion), alpha = .15) +
  scale_linetype_manual(values = c("Observed" = 1, "Predicted counterfactual" = 2)) +
  ylim(0, NA) +
  scale_x_discrete(breaks = seq(5, 53, 6)) +
  theme_minimal() + 
  labs(y = "Count", x = "Week", fill = "Period", color = "Period", linetype = "Scenario",
       subtitle = "", title = "Total cancer-related health services") +
  geom_vline(xintercept = 11, linetype = "dotted", color = "red") + 
  theme(legend.position = "bottom",
        axis.title = element_text(size = 7),
        axis.text = element_text(size = 6),
        plot.subtitle = element_text(size = 7),
        plot.title = element_text(size = 11, face = "bold"))

g1.agg.prest
```

## LME

```{r FIG1, fig.width=6, fig.height=11, message=FALSE, warning=FALSE}

g1.agg.lme <- dat.plots.agg.lme %>% 
  mutate(week = as.numeric(week)) %>% 
  filter(mod.int == "Additive") %>% 
  mutate(exposicion = ifelse(year == 2020, "2020", "2018-2019")) %>% 
  group_by(week, year, exposicion) %>% summarise(count = sum(count),
                                                 yhat = sum(yhat),
                                                 cf = sum(cf),
                                                 ub = sum(ub),
                                                 lb = sum(lb),
                                                 cf_ub = sum(cf_ub),
                                                 cf_lb = sum(cf_lb) ) %>% 
  group_by(week, exposicion)%>% summarise(count = mean(count),
                                          yhat = mean(yhat),
                                          cf = mean(cf),
                                          ub = mean(ub),
                                          lb = mean(lb),
                                          cf_ub = mean(cf_ub),
                                          cf_lb = mean(cf_lb) ) %>% 
  ggplot(aes(x = week, y = count, fill = exposicion)) +
  geom_point(alpha = .3, aes(color = exposicion), size = 1.5) +
  geom_line(aes(x = week, y = yhat, color = exposicion, linetype = "Observed")) +
  geom_ribbon(aes(ymin = lb, ymax = ub, group = exposicion), alpha = .3) +
  geom_line(aes(x = week, y = cf, color = exposicion, linetype = "Predicted counterfactual"), 
            size = .3, name = "bla") +
  geom_ribbon(aes(ymin = cf_lb, ymax = cf_ub, group = exposicion), alpha = .15) +
  scale_linetype_manual(values = c("Observed" = 1, "Predicted counterfactual" = 2)) +
  ylim(0, NA) +
  theme_minimal() +
  scale_x_continuous(breaks = seq(5, 53, 6)) +
  theme(panel.grid.minor.x = element_blank())+
  labs(y = "Count", x = "Week", fill = "Period", color = "Period", linetype = "Scenario",
       subtitle = "", title = "Total cancer sick leaves") +
  geom_vline(xintercept = 11, linetype = "dotted", color = "red") + 
  theme(legend.position = "bottom",
        axis.title = element_text(size = 7),
        axis.text = element_text(size = 6),
        plot.subtitle = element_text(size = 8),
        plot.title = element_text(size = 11, face = "bold"))

g1.agg.lme


```

## Combine

```{r FIG1, fig.width=6, fig.height=11, message=FALSE, warning=FALSE}

g1.prest.lme <- ggarrange(g1.agg.prest, g1.agg.lme, ncol = 1,
        common.legend = T, legend.grob = get_legend(g1.agg.prest), legend = "top")

g1.prest.lme


g1 <- ggarrange(g1.ges, g1.prest.lme, ncol = 2)

g1

ggsave(plot = g1,
       filename = "all services/AJPH fig1.pdf", 
       device = "pdf",
       dpi = "retina",
       width = 12, height = 8)
```