---
title: "Modelos de serie de tiempo interrumpida para caída en lme oncológicas por tipo y previsión"
output: 
---

```{r RMD SETTINGS, message=FALSE, warning=FALSE, include=FALSE}
rm(list = ls()); gc() 
knitr::opts_knit$set(root.dir = "/Users/Fran/Dropbox (Personal)/Analisis IMED/lme")
knitr::opts_chunk$set(include = FALSE,
                      echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

```{r LIBRERIAS, message=FALSE, warning=FALSE, include=FALSE}
library(data.table)
library(tidyverse)
library(MASS)
library(sjPlot)
```

# 1. Datos

```{r LOAD AND PREPARE SAVED DATA GROUPED BY WEEK}
load("/Users/Fran/Dropbox (Personal)/Analisis IMED/lme/output/DB/licencias_cancer_2018.RData")

tipo_cancer<-read.csv("/Users/Fran/Dropbox (Personal)/Analisis IMED/lme/Tipo cáncer para modelos.csv") 

licencias_cancer_2018<-left_join(licencias_cancer_2018, tipo_cancer, by=c("cie10" = "cie10"))
sum(licencias_cancer_2018$n_lme)

lme_modelos_agregados <- licencias_cancer_2018 %>% 
  # FILTRO
  filter(!(Tipo_cancer=="Testicular" & sexo_trabajador=="F"), 
         !(Tipo_cancer=="Mama" & sexo_trabajador=="M"), 
         !(Tipo_cancer=="Prostata" & sexo_trabajador=="F"),
         prevision %in% c("FONASA", "ISAPRE"), !is.na(grupo_edad_2), 
         !is.na(sexo_trabajador))  %>% 
  group_by(date_wk, Cancer_type, prevision, sexo_trabajador, grupo_edad_2) %>% 
  summarise(n_lme=sum(n_lme))
sum(lme_modelos_agregados$n_lme)

lme.2018.dt <- as.data.table(lme_modelos_agregados)

lme_modelos_agregados <- lme.2018.dt[
  , time := as.numeric(factor(date_wk, labels = 0:156)) - 1  ][
    , time_after := ifelse(time < 115, 0, (time - 115 ))  ]

rm(lme.2018.dt)

lme_modelos_agregados <- lme_modelos_agregados  %>% 
  # VARIABLES NUEVAS Y MODIFICADAS
  mutate(pandemia = ifelse(date_wk < as.Date("2020-03-15"), 0, 1),
         grupo_edad_2 = relevel(grupo_edad_2, "[40,50)"),
         sexo_trabajador = as.factor(sexo_trabajador),
         sexo_trabajador = relevel(sexo_trabajador, "M"),
         year=lubridate::year(date_wk),
         week=lubridate::week(date_wk),
         prevision = as.factor(prevision),
         week = as.factor(week),
         Cancer_type = as.factor (Cancer_type)) %>% 
  rename(grupo_edad = grupo_edad_2)

lme_modelos_agregados <- droplevels(lme_modelos_agregados)

sum(lme_modelos_agregados$n_lme)

dat.tipo <- lme_modelos_agregados %>% 
  rename(edad_cat = grupo_edad,
         sexo = sexo_trabajador, 
         count = n_lme)

prevision <- levels(dat.tipo$prevision)
tipo_cancer<- levels(dat.tipo$Cancer_type)

cancer_sexo <-c("Breast", "Cervical", "Ovarian", "Testicular", "Prostate")

 
```

```{r MODELO POR TIPO Y PREVISION}

sets <- list()

for (i in prevision){
  
  for (j in tipo_cancer){
    
    sets[[i]][[j]] <- dat.tipo[prevision == i][Cancer_type == j]
  }
}


formulas <- list(
  as.formula(count ~ edad_cat + sexo + year + week + pandemia + time + pandemia:time_after),
  as.formula(count ~ edad_cat + year + week + pandemia + time + pandemia:time_after)
)


models <- list()

for (i in prevision){
  
  for (j in 1:17){
    
    data <- sets[[i]][[j]]
    
    if (unique(data$Cancer_type) %in% cancer_sexo){
      
      models[[i]][[j]] <- glm.nb(formulas[[2]], data = data)
  
    } else {
      
      models[[i]][[j]] <- glm.nb(formulas[[1]], data = data)
      
    }
  }
}


save(models, file = "/Users/Fran/Dropbox (Personal)/Analisis IMED/lme/output/modelos/nb sti caida lme/20210315 sti caida lme por tipo y prevision.RData" )

# load(file = "/Users/Fran/Dropbox (Personal)/Analisis IMED/lme/output/modelos/nb sti caida lme/20210315 sti caida lme por tipo y prevision.RData")
```

## 2.1 Tablas modelos

```{r}
tab.models <- data.table()

for (i in prevision){
  
  for (j in 1:17){
    
  summ <- summary(models[[i]][[j]])
  mod.res <- as.data.frame(summ$coefficients)
  mod.res$Model <- i
  mod.res$Grupo <- tipo_cancer[j]
  mod.res$Vars <- rownames(summ$coefficients)

  tab.models <- rbind(tab.models, mod.res)

  }
}

rm(summ, mod.res, i)

confint.models <- data.table()

for (i in prevision){
  
  for (j in 1:17){
  
  conf <- confint(models[[i]][[j]])
  conf.res <- as.data.frame(conf)
  conf.res$Model <- i
  conf.res$Grupo <- tipo_cancer[j]
  conf.res$Vars <- rownames(conf)

  confint.models <- rbind(confint.models, conf.res)
  
  }
}
 
rm(conf, conf.res, i)

tab.models <- cbind(tab.models, confint.models[,c(1:2)])

invlink <- models[[1]][[1]]$family$linkinv

. <- tab.models[
  , IRR := invlink(Estimate) ][
  , IC_lower := invlink(`2.5 %`) ][
  , IC_upper := invlink(`97.5 %`) ]

tab.models <- .

save(tab.models, file = "/Users/Fran/Dropbox (Personal)/Analisis IMED/lme/output/tab/tab nb sti/20210315 coef sti por tipo y prevision.RData")

# load(file = "/Users/Fran/Dropbox (Personal)/Analisis IMED/lme/output/tab/tab nb sti/20210315 coef sti por tipo y prevision.RData")
```


## 2.2 Gráfico de coeficientes de modelos

```{r fig.height=10, fig.width=6}
tab.models %>% 
  ggplot(aes(x = IRR, y = Vars)) +
  geom_point()
```

```{r fig.height=10, fig.width=10}
g.coeff <- tab.models %>% 
  filter(Vars %in% c("edad_cat[0,10)", "edad_cat[10,20)", "edad_cat[20,30)", 
                     "edad_cat[30,40)", "edad_cat[50,60)", "edad_cat[60,70)", "edad_cat[70,80)", 
                     "sexoF", "pandemia", "pandemia:time_after", "time")) %>% 
  ggplot(aes(x = IRR, y = Vars)) +
  geom_point(aes(color = Model)) +
  geom_errorbarh(aes(xmin = IC_lower, xmax = IC_upper, color = Model), alpha = .5) +
  geom_vline(xintercept = 1, alpha = .3, linetype = 2) +
  facet_wrap("Grupo", ncol = 6, scales = "free_x") +
  labs(color = "Insurance") +
  theme(legend.position = "bottom")


ggsave(g.coeff, 
       filename = "/Users/Fran/Dropbox (Personal)/Analisis IMED/lme/output/graf/2020/tipo cancer/coef modelos por tipo.png", 
       device = "png",
       dpi = "retina",
       width = 12, height = 8)
```

# 3. Predicciones

```{r PREDICTED DB}
dat.plots.list <- list()

for (i in prevision){
  
  for (j in 1:17){
    
  dat.cf <- sets[[i]][[j]]
  dat.cf$pandemia <- 0

  dat.plots.temp <- sets[[i]][[j]]

  ilink <- family(models[[i]][[j]])$linkinv
  
  pred <- predict(models[[i]][[j]], se.fit = T)
  yhat <- pred$fit
  se <- pred$se.fit
  
  dat.plots.temp$yhat <- ilink(yhat)
  dat.plots.temp$ub <- ilink(yhat + (1.96*se))
  dat.plots.temp$lb <- ilink(yhat - (1.96*se))
  
  
  pred.cf <- predict(models[[i]][[j]], newdata = dat.cf, se.fit = T)
  cf <- pred.cf$fit
  cf.se <- pred.cf$se.fit
  
  dat.plots.temp$cf <- ilink(cf)
  dat.plots.temp$cf_ub <- ilink(cf + (1.96*cf.se))
  dat.plots.temp$cf_lb <- ilink(cf - (1.96*cf.se))
  
  dat.plots.list[[i]][[j]] <- dat.plots.temp
  
  rm(dat.cf, dat.plots.temp, ilink, pred, yhat, se, pred.cf, cf, cf.se)
    
  }
}
```

```{r RECODE AND BIND PREDICTED DB}

dat.plots <- data.table()

for (i in prevision){
  
  for (j in 1:17){
    
  dat.plots <- rbind(dat.plots, dat.plots.list[[i]][[j]])
  }
}

rm(dat.plots.list)

save(dat.plots, file = "/Users/Fran/Dropbox (Personal)/Analisis IMED/lme/output/DB/20210315 DB predichos nb sti por tipo y prevision")
```

# 4. Plots

## 4.1 Serie completa


```{r fig.height=12, fig.width=8}
g1.c <- dat.plots %>% 
  group_by(date_wk, prevision, Cancer_type) %>% summarise(count = sum(count),
                                  yhat = sum(yhat),
                                  cf = sum(cf),
                                  ub = sum(ub),
                                  lb = sum(lb),
                                  cf_ub = sum(cf_ub),
                                  cf_lb = sum(cf_lb)) %>% 
  ggplot(aes(x = date_wk, y = count)) +
  geom_point(aes(color = prevision), alpha = .3) +
  geom_line(aes(x = date_wk, y = yhat, color = prevision)) +
  geom_ribbon(aes(ymin = lb, ymax = ub, fill = prevision), alpha = .3) +
  geom_line(aes(x = date_wk, y = cf, color = prevision), linetype = 2, size = .3) +
  geom_ribbon(aes(ymin = cf_lb, ymax = cf_ub, fill = prevision), alpha = .15) +
  
  facet_grid(Cancer_type ~ ., scales = "free") +
  
  ylim(0, NA) +
  theme_minimal() + 
  labs(y = "Count", x = "Date", fill = "Previsión", color = "Previsión",
       title = "by insurance") +
  geom_vline(xintercept = as.Date("2020-03-15"), linetype = "dotted", color = "red") +
  theme(legend.position = "bottom",
        axis.title = element_text(size = 7),
        axis.text = element_text(size = 6),
        plot.subtitle = element_text(size = 10),
        plot.title = element_text(size = 12))
  
g1.c

ggsave(g1.c, 
       filename = "/Users/Fran/Dropbox (Personal)/Analisis IMED/lme/output/graf/2020/tipo cancer/serie completa por tipo prevision.png", 
       device = "png",
       dpi = "retina",
       width = 12, height = 8)
```

## 4.2 Exposición


```{r fig.height=12, fig.width=5, warning=F}
g2.c <- dat.plots %>% 
  mutate(week = as.numeric(week)) %>% 
  mutate(exposicion = ifelse(year == 2020, "2020", "2018-2019"),
         cf = ifelse(exposicion == "2020" & pandemia != 0, cf, NA),
         cf_ub = ifelse(exposicion == "2020" & pandemia != 0, cf_ub, NA),
         cf_lb = ifelse(exposicion == "2020" & pandemia != 0, cf_lb, NA)) %>% 
  group_by(week, year, exposicion, prevision, Cancer_type) %>% summarise(count = sum(count),
                                                 yhat = sum(yhat),
                                                 cf = sum(cf),
                                                 ub = sum(ub),
                                                 lb = sum(lb),
                                                 cf_ub = sum(cf_ub),
                                                 cf_lb = sum(cf_lb) ) %>% 
  group_by(week, exposicion, prevision, Cancer_type)%>% summarise(count = mean(count),
                                          yhat = mean(yhat),
                                          cf = sum(cf),
                                          ub = mean(ub),
                                          lb = mean(lb),
                                          cf_ub = mean(cf_ub),
                                          cf_lb = mean(cf_lb) ) %>% 
  ggplot(aes(x = week, y = count, fill = exposicion))+
  
  geom_point(alpha = .3, aes(color = exposicion), size = 1.5) +
  geom_line(aes(x = week, y = yhat, color = exposicion, linetype = "Observed")) +
  geom_ribbon(aes(ymin = lb, ymax = ub, group = exposicion), alpha = .3) +

  geom_line(aes(x = week, y = cf, color = exposicion, linetype = "Predicted counterfactual"), size = .3, name = "bla") +
  geom_ribbon(aes(ymin = cf_lb, ymax = cf_ub, group = exposicion), alpha = .15) +
  scale_linetype_manual(values = c("Observed" = 1, "Predicted counterfactual" = 2)) +
  
  facet_grid(Cancer_type ~ prevision, scales = "free") + 
  
  ylim(0, NA) +
  theme_minimal() + 
  labs(y = "Count", x = "Week", fill = "Period", color = "Period", linetype = "Scenario",
       title = "Sick leaves due to Cancer",
       subtitle = "by insurance") +
  geom_vline(xintercept = 11, linetype = "dotted", color = "red") + 
  theme(legend.position = "bottom",
        axis.title = element_text(size = 7),
        axis.text = element_text(size = 6),
        plot.subtitle = element_text(size = 10),
        plot.title = element_text(size = 12))

g2.c

#ggsave(g2.c, 
#       filename = "/Users/Fran/Dropbox (Personal)/Analisis IMED/lme/output/graf/2020/tipo cancer/serie 2020 vs anterior por tipo prevision.png", 
#       device = "png",
#       dpi = "retina",
#       width = 12, height = 15)
```



