---
title: "Modelos de serie de tiempo interrumpida para caída en prestaciones oncológicas"
output: 
---

#

```{r LIBRERIAS, message=FALSE, warning=FALSE, include=FALSE}
library(data.table)
library(tidyverse)
library(MASS)
library(sjPlot)
```

# 1. Datos

```{r LOAD AND PREPARE SAVED DATA GROUPED BY WEEK}
load("output/DB/DB para modelos agregada.RData")

prest <- levels(dat.ag[,grupo.trz])
prest.sexo <- as.character(unique(dat.ag[, .(grupo.trz = grupo.trz, grp.cancer = grp.cancer)][
                            !(grp.cancer %in% c("Prostate Cancer", "Breast Cancer", 
                                                "Cervical Cancer"))][
                                       order(grupo.trz)  ][ , grupo.trz]))
dat.ag <- dat.ag[
  , week := as.factor(week)][
  !(grupo.trz == prest[5] & edad_cat == "[0,10)")][
  !(grupo.trz == prest[8] & edad_cat == "[0,10)")][
  !(grupo.trz == prest[15] & edad_cat %in% c("[0,10)", "[10,20)"))][
  , pandemia := cuarentenas][, cuarentenas := NULL][
  , prevision := factor(prevision, labels = c("Public", "Private"))]

```


# 2. Modelo efectos fijos

```{r MODELO SEXO POR PRESTACION}

sets <- list()

for (i in levels(dat.ag$sexo)){
  
  for (j in prest.sexo){
    
    sets[[i]][[j]] <- dat.ag[sexo == i][grupo.trz == j]
  }
}


formulas <- as.formula(count ~ edad_cat + prevision + year + week + pandemia + time + pandemia:time_after)


models <- list()

for (i in levels(dat.ag$sexo)){
  
  for (j in 1:9){
    
    data <- sets[[i]][[j]]
    
    models[[i]][[j]] <- glm.nb(formulas, data = data)
  
  }
}


save(models, file = "output/models/sti x sexo.RData" )

```

## 2.1 Tablas modelos

```{r}
load(file = "output/models/sti x sexo.RData")

tab.models <- data.table()

prest.eng <- c("Outpatient Visit", "Antigens\n(Ca 125, Ca 15-3, Ca 19-9, Cea)", "Biopsies", "Neoplastic Cells" , "PET-CT", "FOBT", "Sigmoidoscopy and Colonoscopy", "Upper GI endoscopy ", "Urease test")

for (i in levels(dat.ag$sexo)){
  
  for (j in 1:9){
    
  summ <- summary(models[[i]][[j]])
  mod.res <- as.data.frame(summ$coefficients)
  mod.res$Model <- i
  mod.res$Grupo <- prest.eng[j]
  mod.res$Vars <- rownames(summ$coefficients)

  tab.models <- rbind(tab.models, mod.res)

  }
}

rm(summ, mod.res, i)

confint.models <- data.table()

for (i in levels(dat.ag$sexo)){
  
  for (j in 1:9){
  
  conf <- confint(models[[i]][[j]])
  conf.res <- as.data.frame(conf)
  conf.res$Model <- i
  conf.res$Grupo <- prest.eng[j]
  conf.res$Vars <- rownames(conf)

  confint.models <- rbind(confint.models, conf.res)
  
  }
}
 
rm(conf, conf.res, i)

tab.models <- cbind(tab.models, confint.models[,c(1:2)])

invlink <- models[[1]][[1]]$family$linkinv

. <- tab.models[
  , IRR := invlink(Estimate) ][
  , IC_lower := invlink(`2.5 %`) ][
  , IC_upper := invlink(`97.5 %`) ]

tab.models <- .

save(tab.models, file = "output/tabs/coef sti sexo.RData")

```

## 2.2 Gráfico de coeficientes de modelos

```{r}
load(file = "output/tabs/coef sti sexo.RData")
```

```{r fig.height=10, fig.width=6}
tab.models %>% 
  ggplot(aes(x = IRR, y = Vars)) +
  geom_point()
```

```{r fig.height=10, fig.width=10}
tab.plot <- tab.models %>% 
  filter(Vars %in% c("edad_cat[0,10)", "edad_cat[10,20)", "edad_cat[20,30)", 
                     "edad_cat[30,40)", "edad_cat[50,60)", "edad_cat[60,70)", "edad_cat[70,80)", 
                     "previsionPrivate", "pandemia", "pandemia:time_after", "time")) %>% 
  ggplot(aes(x = IRR, y = Vars)) +
  geom_point(aes(color = Model)) +
  geom_errorbarh(aes(xmin = IC_lower, xmax = IC_upper, color = Model), alpha = .5) +
  geom_vline(xintercept = 1, alpha = .3, linetype = 2) +
  facet_wrap("Grupo", ncol = 5, scales = "free_x") +
  labs(color = "Insurance") +
  theme(legend.position = "bottom")

tab.plot

ggsave(plot = tab.plot,
       filename = "output/plots/tab plot inter sexo adit.png", 
       device = "png",
       dpi = "retina",
       width = 10, height = 10)
```


# 3. Predicciones

```{r PREDICTED DB}
dat.plots.list <- list()

for (i in levels(dat.ag$sexo)){
  
  for (j in 1:9){
    
  dat.cf <- sets[[i]][[j]]
  dat.cf$pandemia <- 0

  dat.plots.temp <- sets[[i]][[j]]

  ilink <- family(models[[i]][[j]])$linkinv
  
  pred <- predict(models[[i]][[j]], se.fit = T)
  yhat <- pred$fit
  se <- pred$se.fit
  
  dat.plots.temp$yhat <- ilink(yhat)
  dat.plots.temp$ub <- ilink(yhat + (1.96*se))
  dat.plots.temp$lb <- ilink(yhat - (1.96*se))
  
  
  pred.cf <- predict(models[[i]][[j]], newdata = dat.cf, se.fit = T)
  cf <- pred.cf$fit
  cf.se <- pred.cf$se.fit
  
  dat.plots.temp$cf <- ilink(cf)
  dat.plots.temp$cf_ub <- ilink(cf + (1.96*cf.se))
  dat.plots.temp$cf_lb <- ilink(cf - (1.96*cf.se))
  
  dat.plots.list[[i]][[j]] <- dat.plots.temp
  
  rm(dat.cf, dat.plots.temp, ilink, pred, yhat, se, pred.cf, cf, cf.se)
    
  }
}
```

```{r RECODE AND BIND PREDICTED DB}
for (i in levels(dat.ag$sexo)){
  
  for (j in 1:9){
    
  levels(dat.plots.list[[i]][[j]]$grp.cancer) <- c("General Oncological Services", 
                                                   "Colorectal Cancer", 
                                                   "Cervical Cancer", "Gastric Cancer", 
                                                   "Breast Cancer", "Prostate Cancer")

  levels(dat.plots.list[[i]][[j]]$grupo.trz) <- c("Outpatient Visit", "Antigens\n(Ca 125, 
                                                  Ca 15-3, Ca 19-9, Cea)", 
                                   "Biopsies",   "Neoplastic Cells" , "PET-CT", 
                                 "FOBT", "Sigmoidoscopy and Colonoscopy", 
                                 "Cervical Biopsy", "Colposcopy", "Smear (PAP) test", 
                                 "Upper GI endoscopy ", "Urease test", 
                                 "Breast US", "Mammography", "Breast MRI",
                                 "PSA", "Prostate US")
  }
}

dat.plots <- data.table()

for (i in levels(dat.ag$sexo)){
  
  for (j in 1:9){
    
  dat.plots <- rbind(dat.plots, dat.plots.list[[i]][[j]])
  }
}

rm(dat.plots.list)

save(dat.plots, file = "output/DB/DB predichos nb sti x sexo.RData")

```

# 4. Plots

```{r}
load("output/DB/DB predichos nb sti x sexo.RData")
```

## 4.1 Serie completa

```{r fig.height=8, fig.width=8}
g1.a <- dat.plots %>% 
  group_by(date_wk, grupo.trz) %>% summarise(count = sum(count),
                                  yhat = sum(yhat),
                                  cf = sum(cf),
                                  ub = sum(ub),
                                  lb = sum(lb),
                                  cf_ub = sum(cf_ub),
                                  cf_lb = sum(cf_lb)) %>% 
  ggplot(aes(x = date_wk, y = count)) +
  geom_point(alpha = .3) +
  geom_line(aes(x = date_wk, y = yhat)) +
  geom_ribbon(aes(ymin = lb, ymax = ub), alpha = .3) +
  geom_line(aes(x = date_wk, y = cf), linetype = 2, size = .3) +
  geom_ribbon(aes(ymin = cf_lb, ymax = cf_ub), alpha = .15) +
  
  facet_wrap("grupo.trz", scales = "free", ncol = 3) +
  
  ylim(0, NA) +
  theme_minimal() + 
  labs(y = "Count", x = "Date", 
       title = "Additive model") +
  geom_vline(xintercept = as.Date("2020-03-15"), linetype = "dotted", color = "red") +
  theme(legend.position = "bottom",
        axis.title = element_text(size = 7),
        axis.text = element_text(size = 6),
        plot.subtitle = element_text(size = 10),
        plot.title = element_text(size = 12))
  
g1.a
```

```{r fig.height=12, fig.width=8}
g1.c <- dat.plots %>% 
  group_by(date_wk, sexo, grupo.trz) %>% summarise(count = sum(count),
                                  yhat = sum(yhat),
                                  cf = sum(cf),
                                  ub = sum(ub),
                                  lb = sum(lb),
                                  cf_ub = sum(cf_ub),
                                  cf_lb = sum(cf_lb)) %>% 
  ggplot(aes(x = date_wk, y = count)) +
  geom_point(aes(color = sexo), alpha = .3) +
  geom_line(aes(x = date_wk, y = yhat, color = sexo)) +
  geom_ribbon(aes(ymin = lb, ymax = ub, fill = sexo), alpha = .3) +
  geom_line(aes(x = date_wk, y = cf, color = sexo), linetype = 2, size = .3) +
  geom_ribbon(aes(ymin = cf_lb, ymax = cf_ub, fill = sexo), alpha = .15) +
  
  facet_grid(grupo.trz ~ ., scales = "free") +
  
  ylim(0, NA) +
  theme_minimal() + 
  labs(y = "Count", x = "Date", fill = "Sex", color = "Sex",
       title = "by sex") +
  geom_vline(xintercept = as.Date("2020-03-15"), linetype = "dotted", color = "red") +
  theme(legend.position = "bottom",
        axis.title = element_text(size = 7),
        axis.text = element_text(size = 6),
        plot.subtitle = element_text(size = 10),
        plot.title = element_text(size = 12))
  
g1.c
```

## 4.2 Exposición

```{r fig.height=8, fig.width=8, warning=F}
g2.a <- dat.plots %>% 
  mutate(week = as.numeric(week)) %>% 
 mutate(exposicion = ifelse(year == 2020, "2020", "2018-2019"),
         cf = ifelse(exposicion == "2020" & pandemia != 0, cf, NA),
         cf_ub = ifelse(exposicion == "2020" & pandemia != 0, cf_ub, NA),
         cf_lb = ifelse(exposicion == "2020" & pandemia != 0, cf_lb, NA) ) %>% 
  group_by(week, year, exposicion, grupo.trz) %>% summarise(count = sum(count),
                                                 yhat = sum(yhat),
                                                 cf = sum(cf),
                                                 ub = sum(ub),
                                                 lb = sum(lb),
                                                 cf_ub = sum(cf_ub),
                                                 cf_lb = sum(cf_lb) ) %>% 
  group_by(week, exposicion, grupo.trz)%>% summarise(count = mean(count),
                                          yhat = mean(yhat),
                                          cf = sum(cf),
                                          ub = mean(ub),
                                          lb = mean(lb),
                                          cf_ub = mean(cf_ub),
                                          cf_lb = mean(cf_lb) ) %>% 
  
  ggplot(aes(x = week, y = count, fill = exposicion))+
  
  geom_point(alpha = .3, aes(color = exposicion), size = 1.5) +
  geom_line(aes(x = week, y = yhat, color = exposicion, linetype = "Observed")) +
  geom_ribbon(aes(ymin = lb, ymax = ub, group = exposicion), alpha = .3) +

  geom_line(aes(x = week, y = cf, color = exposicion, linetype = "Predicted counterfactual"), 
            size = .3, name = "bla") +
  geom_ribbon(aes(ymin = cf_lb, ymax = cf_ub, group = exposicion), alpha = .15) +
  scale_linetype_manual(values = c("Observed" = 1, "Predicted counterfactual" = 2)) +
  
  facet_wrap("grupo.trz", scales = "free", ncol = 3) +
  
  ylim(0, NA) +
  theme_minimal() + 
  labs(y = "Count", x = "Week", fill = "Period", color = "Period", linetype = "Scenario",
       title = "Health Services associated with Cancer") +
  geom_vline(xintercept = 11, linetype = "dotted", color = "red") + 
  theme(legend.position = "bottom",
        axis.title = element_text(size = 7),
        axis.text = element_text(size = 6),
        plot.subtitle = element_text(size = 10),
        plot.title = element_text(size = 12))

g2.a
```

```{r fig.height=12, fig.width=12, warning=F}
g2.c <- dat.plots %>% 
  mutate(week = as.numeric(week)) %>% 
  mutate(exposicion = ifelse(year == 2020, "2020", "2018-2019"),
         cf = ifelse(exposicion == "2020" & pandemia != 0, cf, NA),
         cf_ub = ifelse(exposicion == "2020" & pandemia != 0, cf_ub, NA),
         cf_lb = ifelse(exposicion == "2020" & pandemia != 0, cf_lb, NA)) %>% 
  group_by(week, year, exposicion, prevision, grupo.trz) %>% summarise(count = sum(count),
                                                 yhat = sum(yhat),
                                                 cf = sum(cf),
                                                 ub = sum(ub),
                                                 lb = sum(lb),
                                                 cf_ub = sum(cf_ub),
                                                 cf_lb = sum(cf_lb) ) %>% 
  group_by(week, exposicion, prevision, grupo.trz)%>% summarise(count = mean(count),
                                          yhat = mean(yhat),
                                          cf = sum(cf),
                                          ub = mean(ub),
                                          lb = mean(lb),
                                          cf_ub = mean(cf_ub),
                                          cf_lb = mean(cf_lb) ) %>% 
  ggplot(aes(x = week, y = count, fill = exposicion))+
  
  geom_point(alpha = .3, aes(color = exposicion), size = 1.5) +
  geom_line(aes(x = week, y = yhat, color = exposicion, linetype = "Observed")) +
  geom_ribbon(aes(ymin = lb, ymax = ub, group = exposicion), alpha = .3) +

  geom_line(aes(x = week, y = cf, color = exposicion, linetype = "Predicted counterfactual"), size = .3, name = "bla") +
  geom_ribbon(aes(ymin = cf_lb, ymax = cf_ub, group = exposicion), alpha = .15) +
  scale_linetype_manual(values = c("Observed" = 1, "Predicted counterfactual" = 2)) +
  
  facet_grid(grupo.trz ~ prevision, scales = "free") + 
  
  ylim(0, NA) +
  theme_minimal() + 
  labs(y = "Count", x = "Week", fill = "Period", color = "Period", linetype = "Scenario",
       title = "Health Services associated with Cancer",
       subtitle = "by sex") +
  geom_vline(xintercept = 11, linetype = "dotted", color = "red") + 
  theme(legend.position = "bottom",
        axis.title = element_text(size = 7),
        axis.text = element_text(size = 6),
        plot.subtitle = element_text(size = 10),
        plot.title = element_text(size = 12))

g2.c
```


# Guardar gráficos

```{r}
ggsave(plot = g1.a,
       filename = "output/plots/serie completa inter sexo adit.png", 
       device = "png",
       dpi = "retina",
       width = 8, height = 8)

ggsave(plot = g1.c,
       filename = "output/plots/serie completa inter sexo sexo.png", 
       device = "png",
       dpi = "retina",
       width = 8, height = 12)
```

```{r}
ggsave(plot = g2.a,
       filename = "output/plots/serie 2020 vs anterior inter sexo adit.png", 
       device = "png",
       dpi = "retina",
       width = 8, height = 8)

ggsave(plot = g2.c,
       filename = "output/plots/serie 2020 vs anterior inter sexo sexo.png", 
       device = "png",
       dpi = "retina",
       width = 12, height = 12)
```